steps:
  # Step 1: Build Angular app
  - name: 'node:18'
    dir: 'Cartify'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build --configuration=production

  # Step 2: Copy Angular dist to server public folder (if serving via Express)
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p CartifyWebApi/public
        cp -r Cartify/dist/* CartifyWebApi/public/

  # Step 3: Build and push Docker image for backend
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'CartifyWebApi'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cartify-api', '.']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'cartify-api',
           '--image', 'gcr.io/$PROJECT_ID/cartify-api',
           '--region', 'us-central1',
           '--platform', 'managed',
           '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/cartify-api'
