# Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - dekomart

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install Chrome dependencies and Puppeteer (safe mode)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip \
            fonts-liberation libappindicator3-1 \
            libatk-bridge2.0-0t64 libatk1.0-0t64 libcups2t64 libdbus-1-3 \
            libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 \
            libxcomposite1 libxdamage1 libxrandr2 xdg-utils \
            libasound2t64
          cd DekomartWebApi
          npm install
          npx --yes puppeteer browsers install chrome || echo "Puppeteer install fallback failed"
      - name: Build project
        run: |
          cd DekomartWebApi
          npm run build || echo "No build step defined, continuing..."
      - name: Zip contents for deployment
        run: |
          cd DekomartWebApi
          zip -r ../release.zip .
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
      runs-on: ubuntu-latest
      needs: build
      permissions:
        id-token: write #This is required for requesting the JWT
        contents: read #This is required for actions/checkout

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: node-app
        
        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F05CADCB07EF4DBA806FAD48A5DA7615 }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5487FA7E58A04B2E9F89A23D14115C50 }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C95EE00D5D3141288040E540967DEE8C }}

        - name: 'Deploy to Azure Web App'
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v3
          with:
            app-name: 'dekomartwebapi'
            slot-name: 'Production'
            package: .
          