name: Release CartifyWebApi
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to App Engine
        run: |
          cd CartifyWebApi
          gcloud app deploy app.yaml --quiet
