name: Build and deploy Node.js app to Azure Web App - dekomart

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install system dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip \
            fonts-liberation libappindicator3-1 \
            libatk-bridge2.0-0t64 libatk1.0-0t64 libcups2t64 libdbus-1-3 \
            libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 \
            libxcomposite1 libxdamage1 libxrandr2 xdg-utils \
            libasound2t64

      - name: Install dependencies and Chrome for Puppeteer
        run: |
          cd CartifyWebApi
          npm install
          export PUPPETEER_CACHE_DIR="./.puppeteer-cache"
          export PUPPETEER_DOWNLOAD_PATH="$PUPPETEER_CACHE_DIR"
          npx puppeteer browsers install chrome

      - name: Build project
        run: |
          cd CartifyWebApi
          npm run build || echo "No build step defined"

      - name: Zip contents for deployment
        run: |
          cd CartifyWebApi
          zip -r ../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dekomart'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4304D5725DAB4782ADCE32F7E6F86779 }}
